spring:
  application:
    name: MovieAPI
  main:
    banner-mode : off
  logging:
    level:
      root: warn

  datasource:
    url: jdbc:mysql://localhost:3306/movies_2
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hussein.elbhrawy74@gmail.com
    password: dqwhqjsalxyivoos
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"

app:
  jwt-secret: 3a4a037aa3ee8e56470091e5c57201dd8ea08343d0dc91e63302ffb61f0cabee
#  jwt-expiration-milliseconds: 604800000
  jwt-expiration-milliseconds: 900000
  jwt-refresh-expiration-milliseconds: 604800000









